### ISSUE TITLE
CocoaPod fails to download 8.14.2

### ISSUE THREAD

**Issue by aiartsev** [getsentry/sentry-cocoa#3360]
### Platform

iOS

### Installed

CocoaPods

### Version

Fixed 8.7.2 in the Podfile

### Steps to Reproduce

1. Uninstall CocoaPods (tested both 1.14.0 and 1.13.0)
2. Clear CocoaPods Cache and remove any associated files
3. Re-install CocoaPods (tested both 1.14.0 and 1.13.0)
4. Run `pod install`

### Expected Result

Command succeeds

### Actual Result

Errors out with
### Error

```
JSON::ParserError - Failed to parse JSON at file: '~/.cocoapods/repos/trunk/Specs/a/b/d/Sentry/8.14.2/Sentry.podspec.json'.

unexpected token at ''
/usr/local/Cellar/cocoapods/1.14.0/libexec/gems/cocoapods-core-1.14.0/lib/cocoapods-core/specification/json.rb:66:in `rescue in from_json'
/usr/local/Cellar/cocoapods/1.14.0/libexec/gems/cocoapods-core-1.14.0/lib/cocoapods-core/specification/json.rb:61:in `from_json'
/usr/local/Cellar/cocoapods/1.14.0/libexec/gems/cocoapods-core-1.14.0/lib/cocoapods-core/specification.rb:752:in `from_string'
/usr/local/Cellar/cocoapods/1.14.0/libexec/gems/cocoapods-core-1.14.0/lib/cocoapods-core/specification.rb:726:in `from_file'
/usr/local/Cellar/cocoapods/1.14.0/libexec/gems/cocoapods-core-1.14.0/lib/cocoapods-core/source.rb:188:in `specification'
/usr/local/Cellar/cocoapods/1.14.0/libexec/gems/cocoapods-core-1.14.0/lib/cocoapods-core/specification/set.rb:58:in `block in specification_name'
/usr/local/Cellar/cocoapods/1.14.0/libexec/gems/cocoapods-core-1.14.0/lib/cocoapods-core/specification/set.rb:56:in `each'
/usr/local/Cellar/cocoapods/1.14.0/libexec/gems/cocoapods-core-1.14.0/lib/cocoapods-core/specification/set.rb:56:in `specification_name'
/usr/local/Cellar/cocoapods/1.14.0/libexec/gems/cocoapods-core-1.14.0/lib/cocoapods-core/cdn_source.rb:216:in `search'
/usr/local/Cellar/cocoapods/1.14.0/libexec/gems/cocoapods-core-1.14.0/lib/cocoapods-core/source/aggregate.rb:83:in `block in search'
/usr/local/Cellar/cocoapods/1.14.0/libexec/gems/cocoapods-core-1.14.0/lib/cocoapods-core/source/aggregate.rb:83:in `select'
/usr/local/Cellar/cocoapods/1.14.0/libexec/gems/cocoapods-core-1.14.0/lib/cocoapods-core/source/aggregate.rb:83:in `search'
/usr/local/Cellar/cocoapods/1.14.0/libexec/gems/cocoapods-1.14.0/lib/cocoapods/resolver.rb:416:in `create_set_from_sources'
/usr/local/Cellar/cocoapods/1.14.0/libexec/gems/cocoapods-1.14.0/lib/cocoapods/resolver.rb:385:in `find_cached_set'
/usr/local/Cellar/cocoapods/1.14.0/libexec/gems/cocoapods-1.14.0/lib/cocoapods/resolver.rb:360:in `specifications_for_dependency'
/usr/local/Cellar/cocoapods/1.14.0/libexec/gems/cocoapods-1.14.0/lib/cocoapods/resolver.rb:165:in `search_for'
/usr/local/Cellar/cocoapods/1.14.0/libexec/gems/cocoapods-1.14.0/lib/cocoapods/resolver.rb:274:in `block in sort_dependencies'
/usr/local/Cellar/cocoapods/1.14.0/libexec/gems/cocoapods-1.14.0/lib/cocoapods/resolver.rb:267:in `each'
/usr/local/Cellar/cocoapods/1.14.0/libexec/gems/cocoapods-1.14.0/lib/cocoapods/resolver.rb:267:in `sort_by'
/usr/local/Cellar/cocoapods/1.14.0/libexec/gems/cocoapods-1.14.0/lib/cocoapods/resolver.rb:267:in `sort_by!'
/usr/local/Cellar/cocoapods/1.14.0/libexec/gems/cocoapods-1.14.0/lib/cocoapods/resolver.rb:267:in `sort_dependencies'
/usr/local/Cellar/cocoapods/1.14.0/libexec/gems/molinillo-0.8.0/lib/molinillo/delegates/specification_provider.rb:60:in `block in sort_dependencies'
/usr/local/Cellar/cocoapods/1.14.0/libexec/gems/molinillo-0.8.0/lib/molinillo/delegates/specification_provider.rb:77:in `with_no_such_dependency_error_handling'
/usr/local/Cellar/cocoapods/1.14.0/libexec/gems/molinillo-0.8.0/lib/molinillo/delegates/specification_provider.rb:59:in `sort_dependencies'
/usr/local/Cellar/cocoapods/1.14.0/libexec/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:754:in `push_state_for_requirements'
/usr/local/Cellar/cocoapods/1.14.0/libexec/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:288:in `push_initial_state'
/usr/local/Cellar/cocoapods/1.14.0/libexec/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:210:in `start_resolution'
/usr/local/Cellar/cocoapods/1.14.0/libexec/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:168:in `resolve'
/usr/local/Cellar/cocoapods/1.14.0/libexec/gems/molinillo-0.8.0/lib/molinillo/resolver.rb:43:in `resolve'
/usr/local/Cellar/cocoapods/1.14.0/libexec/gems/cocoapods-1.14.0/lib/cocoapods/resolver.rb:94:in `resolve'
/usr/local/Cellar/cocoapods/1.14.0/libexec/gems/cocoapods-1.14.0/lib/cocoapods/installer/analyzer.rb:1082:in `block in resolve_dependencies'
/usr/local/Cellar/cocoapods/1.14.0/libexec/gems/cocoapods-1.14.0/lib/cocoapods/user_interface.rb:64:in `section'
/usr/local/Cellar/cocoapods/1.14.0/libexec/gems/cocoapods-1.14.0/lib/cocoapods/installer/analyzer.rb:1080:in `resolve_dependencies'
/usr/local/Cellar/cocoapods/1.14.0/libexec/gems/cocoapods-1.14.0/lib/cocoapods/installer/analyzer.rb:125:in `analyze'
/usr/local/Cellar/cocoapods/1.14.0/libexec/gems/cocoapods-1.14.0/lib/cocoapods/installer.rb:422:in `analyze'
/usr/local/Cellar/cocoapods/1.14.0/libexec/gems/cocoapods-1.14.0/lib/cocoapods/installer.rb:244:in `block in resolve_dependencies'
/usr/local/Cellar/cocoapods/1.14.0/libexec/gems/cocoapods-1.14.0/lib/cocoapods/user_interface.rb:64:in `section'
/usr/local/Cellar/cocoapods/1.14.0/libexec/gems/cocoapods-1.14.0/lib/cocoapods/installer.rb:243:in `resolve_dependencies'
/usr/local/Cellar/cocoapods/1.14.0/libexec/gems/cocoapods-1.14.0/lib/cocoapods/installer.rb:162:in `install!'
/usr/local/Cellar/cocoapods/1.14.0/libexec/gems/cocoapods-1.14.0/lib/cocoapods/command/update.rb:63:in `run'
/usr/local/Cellar/cocoapods/1.14.0/libexec/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
/usr/local/Cellar/cocoapods/1.14.0/libexec/gems/cocoapods-1.14.0/lib/cocoapods/command.rb:52:in `run'
/usr/local/Cellar/cocoapods/1.14.0/libexec/gems/cocoapods-1.14.0/bin/pod:55:in `<top (required)>'
/usr/local/Cellar/cocoapods/1.14.0/libexec/bin/pod:25:in `load'
/usr/local/Cellar/cocoapods/1.14.0/libexec/bin/pod:25:in `<main>'
```
and sometimes

### Error

```
JSON::ParserError - Failed to parse JSON at file: '~/.cocoapods/repos/trunk/Specs/a/6/6/SentryPrivate/8.14.2/SentryPrivate.podspec.json'.

unexpected token at ''
/usr/local/Cellar/cocoapods/1.14.0/libexec/gems/cocoapods-core-1.14.0/lib/cocoapods-core/specification/json.rb:66:in `rescue in from_json'
/usr/local/Cellar/cocoapods/1.14.0/libexec/gems/cocoapods-core-1.14.0/lib/cocoapods-core/specification/json.rb:61:in `from_json'
/usr/local/Cellar/cocoapods/1.14.0/libexec/gems/cocoapods-core-1.14.0/lib/cocoapods-core/specification.rb:752:in `from_string'
/usr/local/Cellar/cocoapods/1.14.0/libexec/gems/cocoapods-core-1.14.0/lib/cocoapods-core/specification.rb:726:in `from_file'
/usr/local/Cellar/cocoapods/1.14.0/libexec/gems/cocoapods-core-1.14.0/lib/cocoapods-core/source.rb:188:in `specification'
/usr/local/Cellar/cocoapods/1.14.0/libexec/gems/cocoapods-core-1.14.0/lib/cocoapods-core/specification/set.rb:58:in `block in specification_name'
/usr/local/Cellar/cocoapods/1.14.0/libexec/gems/cocoapods-core-1.14.0/lib/cocoapods-core/specification/set.rb:56:in `each'
/usr/local/Cellar/cocoapods/1.14.0/libexec/gems/cocoapods-core-1.14.0/lib/cocoapods-core/specification/set.rb:56:in `specification_name'
/usr/local/Cellar/cocoapods/1.14.0/libexec/gems/cocoapods-core-1.14.0/lib/cocoapods-core/cdn_source.rb:216:in `search'
/usr/local/Cellar/cocoapods/1.14.0/libexec/gems/cocoapods-core-1.14.0/lib/cocoapods-core/source/aggregate.rb:83:in `block in search'
/usr/local/Cellar/cocoapods/1.14.0/libexec/gems/cocoapods-core-1.14.0/lib/cocoapods-core/source/aggregate.rb:83:in `select'
/usr/local/Cellar/cocoapods/1.14.0/libexec/gems/cocoapods-core-1.14.0/lib/cocoapods-core/source/aggregate.rb:83:in `search'
/usr/local/Cellar/cocoapods/1.14.0/libexec/gems/cocoapods-1.14.0/lib/cocoapods/resolver.rb:416:in `create_set_from_sources'
/usr/local/Cellar/cocoapods/1.14.0/libexec/gems/cocoapods-1.14.0/lib/cocoapods/resolver.rb:385:in `find_cached_set'
/usr/local/Cellar/cocoapods/1.14.0/libexec/gems/cocoapods-1.14.0/lib/cocoapods/resolver.rb:360:in `specifications_for_dependency'
/usr/local/Cellar/cocoapods/1.14.0/libexec/gems/cocoapods-1.14.0/lib/cocoapods/resolver.rb:165:in `search_for'
/usr/local/Cellar/cocoapods/1.14.0/libexec/gems/cocoapods-1.14.0/lib/cocoapods/resolver.rb:274:in `block in sort_dependencies'
/usr/local/Cellar/cocoapods/1.14.0/libexec/gems/cocoapods-1.14.0/lib/cocoapods/resolver.rb:267:in `each'
/usr/local/Cellar/cocoapods/1.14.0/libexec/gems/cocoapods-1.14.0/lib/cocoapods/resolver.rb:267:in `sort_by'
/usr/local/Cellar/cocoapods/1.14.0/libexec/gems/cocoapods-1.14.0/lib/cocoapods/resolver.rb:267:in `sort_by!'
/usr/local/Cellar/cocoapods/1.14.0/libexec/gems/cocoapods-1.14.0/lib/cocoapods/resolver.rb:267:in `sort_dependencies'
/usr/local/Cellar/cocoapods/1.14.0/libexec/gems/molinillo-0.8.0/lib/molinillo/delegates/specification_provider.rb:60:in `block in sort_dependencies'
/usr/local/Cellar/cocoapods/1.14.0/libexec/gems/molinillo-0.8.0/lib/molinillo/delegates/specification_provider.rb:77:in `with_no_such_dependency_error_handling'
/usr/local/Cellar/cocoapods/1.14.0/libexec/gems/molinillo-0.8.0/lib/molinillo/delegates/specification_provider.rb:59:in `sort_dependencies'
/usr/local/Cellar/cocoapods/1.14.0/libexec/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:754:in `push_state_for_requirements'
/usr/local/Cellar/cocoapods/1.14.0/libexec/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:744:in `require_nested_dependencies_for'
/usr/local/Cellar/cocoapods/1.14.0/libexec/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:727:in `activate_new_spec'
/usr/local/Cellar/cocoapods/1.14.0/libexec/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:684:in `attempt_to_activate'
/usr/local/Cellar/cocoapods/1.14.0/libexec/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:254:in `process_topmost_state'
/usr/local/Cellar/cocoapods/1.14.0/libexec/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:182:in `resolve'
/usr/local/Cellar/cocoapods/1.14.0/libexec/gems/molinillo-0.8.0/lib/molinillo/resolver.rb:43:in `resolve'
/usr/local/Cellar/cocoapods/1.14.0/libexec/gems/cocoapods-1.14.0/lib/cocoapods/resolver.rb:94:in `resolve'
/usr/local/Cellar/cocoapods/1.14.0/libexec/gems/cocoapods-1.14.0/lib/cocoapods/installer/analyzer.rb:1082:in `block in resolve_dependencies'
/usr/local/Cellar/cocoapods/1.14.0/libexec/gems/cocoapods-1.14.0/lib/cocoapods/user_interface.rb:64:in `section'
/usr/local/Cellar/cocoapods/1.14.0/libexec/gems/cocoapods-1.14.0/lib/cocoapods/installer/analyzer.rb:1080:in `resolve_dependencies'
/usr/local/Cellar/cocoapods/1.14.0/libexec/gems/cocoapods-1.14.0/lib/cocoapods/installer/analyzer.rb:125:in `analyze'
/usr/local/Cellar/cocoapods/1.14.0/libexec/gems/cocoapods-1.14.0/lib/cocoapods/installer.rb:422:in `analyze'
/usr/local/Cellar/cocoapods/1.14.0/libexec/gems/cocoapods-1.14.0/lib/cocoapods/installer.rb:244:in `block in resolve_dependencies'
/usr/local/Cellar/cocoapods/1.14.0/libexec/gems/cocoapods-1.14.0/lib/cocoapods/user_interface.rb:64:in `section'
/usr/local/Cellar/cocoapods/1.14.0/libexec/gems/cocoapods-1.14.0/lib/cocoapods/installer.rb:243:in `resolve_dependencies'
/usr/local/Cellar/cocoapods/1.14.0/libexec/gems/cocoapods-1.14.0/lib/cocoapods/installer.rb:162:in `install!'
/usr/local/Cellar/cocoapods/1.14.0/libexec/gems/cocoapods-1.14.0/lib/cocoapods/command/update.rb:63:in `run'
/usr/local/Cellar/cocoapods/1.14.0/libexec/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
/usr/local/Cellar/cocoapods/1.14.0/libexec/gems/cocoapods-1.14.0/lib/cocoapods/command.rb:52:in `run'
/usr/local/Cellar/cocoapods/1.14.0/libexec/gems/cocoapods-1.14.0/bin/pod:55:in `<top (required)>'
/usr/local/Cellar/cocoapods/1.14.0/libexec/bin/pod:25:in `load'
/usr/local/Cellar/cocoapods/1.14.0/libexec/bin/pod:25:in `<main>'
```

**Comment by philipphofmann** [comment]
Hey @aiartsev,

I just tried installing Sentry 8.14.2 via CocoaPods with CocoaPods version 1.14.0, and it worked. We had some trouble with releasing Sentry 8.14.2 to CocoaPods. Please try running `pod repo update` and try again. Maybe it fixes your problem.

**Comment by philipphofmann** [comment]
Please reopen this issue if what I suggested in https://github.com/getsentry/sentry-cocoa/issues/3360#issuecomment-1782441268 doesn't work.
